### PR TITLE
Initial addition for Pine64 devices

### PR DESCRIPTION
**Pull request by yeyeto2788**
I will need the output of the `/proc/cpuinfo` and the `/proc/device-tree/model` for a better implementation.

### CODE REVIEW

**Comment by yeyeto2788** [comment]
Output of the latest changes working on the Pinebook running Armbian:
```console
linuxuser@pinebook:~/GitHub/Adafruit_Python_PlatformDetect$ python3 Python 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609] on linux Type "help", "copyright", "credits" or "license" for more information. 
>>> import adafruit_platformdetect 
>>> detector = adafruit_platformdetect.Detector() 
>>> detector.chip.id 
'PINE64' 
>>> detector.board.id 
'PINEBOOK'
```

**Comment by ladyada** [comment]
hi the chip should be the A64 right? there is no chip called 'pine64'?
https://linux-sunxi.org/A64

**Comment by makermelissa** [comment]
Yes, that's correct. The Original Pine64 was actually called the Pine A64.

**Comment by yeyeto2788** [comment]
Yeap, the chip is the AllWinner A64, if you want I can make the change reflecting it. I'll also test the new implementation on other OS.

Shouldn't we detect the board and chip based on OS? I ask this because there is already a method for getting the `BOARD` variable from armbian and it is only used by orange pi boards.

Regards.

**Comment by ladyada** [comment]
no, the chip is set by the hardware - whatever is printed on the microcontroller, it is independant completely from the OS :)

**Comment by yeyeto2788** [comment]
Got it! :P thanks for the clarification. I'll make the changes tomorrow so you guys will have it to review first time in your morning (different working hours)

**Comment by ladyada** [comment]
all good, thank you for working with us :)

**Comment by yeyeto2788** [comment]
My pleasure @ladyada, I'll upload the result once I get home and test it on the PineBook itself. 

After finishing this PR would be great if you or @makermelissa can point me out to the right direction on adding the support on https://github.com/adafruit/Adafruit_Blinka/issues/118 and adding also the Onion Omega board on it (don't want to start making changes out of the blue without a prior guidance :stuck_out_tongue: ).

Also, @makermelissa can you please test this on your Pine64 board and share the `/proc/cpuinfo` file content so I can adapt the code accordingly?

Regards.

**Comment by makermelissa** [comment]
Hi, I'll try to get the `/proc/cpuinfo` to you today sometime.

**Comment by yeyeto2788** [comment]
@makermelissa, no problem. I have tested the new changes just now on the PineBook and this is the result:

```console
linuxuser@pinebook:~/GitHub/Adafruit_Python_PlatformDetect$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_platformdetect
>>> detector = adafruit_platformdetect.Detector()
>>> detector.board.id
'PINEBOOK'
>>> detector.chip.id
'A64'
>>> 
```

In yours it should be working also, but by any chance is not and you want me to change something, let me know.

**Comment by makermelissa** [comment]
Sounds good!

**Comment by makermelissa** [comment]
Looks like I accidentally overwrote my Pine64 SD Card with another image, so I'm needing to reset it back up.

**Comment by yeyeto2788** [comment]
No problem, if you want you can also test it with that distro. 

There might be something we can add to support the detection on that OS

**Comment by makermelissa** [comment]
Oh, I meant I overwrote it with Ubuntu for the Raspberry Pi while testing another PR. Armbian is the preferred one since we've had really good luck with it.

**Comment by lucapinello** [comment]
Hi thanks for adding the support to the Pine64! 

This doesn't work for me in my machine I see this for cat /proc/cpuinfo :
Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
Features	: fp asimd aes pmull sha1 sha2 crc32 
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: Pine64+

and  cat /proc/device-tree/model 

Pine64+

Maybe is it the + at the end?

Thanks!

**Comment by makermelissa** [comment]
What do you get for `cat /proc/device-tree/compatible`?

**Comment by lucapinello** [comment]
Thanks for the quick reply! 

cat /proc/device-tree/compatible
pine64,pine64-plus

**Comment by makermelissa** [comment]
Is that the full string? The one on my board was `pine64,pine64-plusallwinner,sun50i-a64`.

If so, it seems they may have removed the processor from the string, which is causing the chip to not be detected and the board value isn't even checked at that point. That could present problem because of other boards having similar strings.

**Comment by lucapinello** [comment]
Yes this is the full string. Btw I truly appreciate your quick reply and
help!

**Comment by makermelissa** [comment]
Ok, created a new issue at #133. Please make any new comments regarding this issue there.

**Pull request merged**
