### PR TITLE
Support for Orange Pi Zero Plus2 H5

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by makermelissa** [comment]
Could you include this as part of #114 please?  Just add the change to your patch-2 branch and push. Github will update your PR.

**Comment by twa127** [comment]
Hi,

Sorry not sure how to - Could you include this as part of #114 please? Just add the change to your patch-2 branch and push. Github will update your PR

**Comment by makermelissa** [comment]
No worries, I just merged them in for you. :)

**Comment by twa127** [comment]
Thanks for sorting this out for me, sorry for being a bit dim :-))

**Comment by makermelissa** [comment]
It's all good. I was able to sort out another older PR while I was sorting this out.

**Pull request closed without merging**
