### PR TITLE
update boards.py

### PR DESCRIPTION
**Pull request by SimpleTheory**
Added a03141, b03141, and c03141 revision numbers to RASPBERRY_PI_CM4:

- cf. https://github.com/adafruit/Adafruit_Python_PlatformDetect/issues/244

### CODE REVIEW

**Comment by SimpleTheory** [comment]
Don't know why the tests are not passing I only added the rev numbers to line 492, any ideas?

**Comment by makermelissa** [comment]
It looks like you need to run pre-commit: https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

**Comment by SimpleTheory** [comment]
Okay I see. I'll do that later tonight, thanks.

**Comment by SimpleTheory** [comment]
Fixed pre-commit tests see next pull request

**Pull request closed without merging**
