### PR TITLE
Move the U2IF constant definitions to a single file so they are not duplicated

### LINKED ISSUE #174: Duplicate constants in boards and chips
I'm trying to get `pre-commit` working to close #140.

However `pre-commit` fails locally on `pylint` with
```
adafruit_platformdetect/board.py:1:0: R0801: Similar lines in 2 files
==adafruit_platformdetect.constants.boards:119
==adafruit_platformdetect.constants.chips:48
PICO_U2IF = "PICO_U2IF"
FEATHER_U2IF = "FEATHER_U2IF"
ITSYBITSY_U2IF = "ITSYBITSY_U2IF"
QTPY_U2IF = "QTPY_U2IF"
QT2040_TRINKEY_U2IF = "QT2040_TRINKEY_U2IF"
 (duplicate-code)
```
This is detected in the `build.yml` Github action but seems to pass anyway, for example https://github.com/adafruit/Adafruit_Python_PlatformDetect/runs/2797662229?check_suite_focus=true under the Pylint section

Do these need to be defined in both files?

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
This will close #174

This gets `pylint $( find . -path './adafruit*.py' )` to 10/10.
This change will also enable `pre-commit` to succeed when it is installed.

Tested locally on Ubuntu and Raspberry Pi 4.
I don't have a U2IF device to test with.

*NOTE:* This could be a breaking change to anything outside of `PlatformDetect` which directly uses the `boards.XXXX_U2IF` or `chips.XXXX_U2IF` constants. Although, if I understand the design correctly, any external scripts should be using `board.py` and `chip.py` NOT the constants.

### CODE REVIEW

**Comment by makermelissa** [comment]
This change would likely break Blinka, so all of the places such as https://github.com/adafruit/Adafruit_Blinka/blob/main/src/board.py#L227-L240 would need updating.

**Comment by makermelissa** [comment]
There's an easier way. You can just increase https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/main/.pylintrc#L252 to a little bit higher value like 12 or something. A value of 4 is pretty low.

**Comment by lesamouraipourpre** [comment]
> 
> 
> There's an easier way. You can just increase https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/main/.pylintrc#L252 to a little bit higher value like 12 or something. A value of 4 is pretty low.

Unfortunately, that doesn't fix it - it was the first thing I tried.
The problem is because `board.py` imports `boards` and `chips` which both define `PICO_U2IF`, `FEATHER_U2IF`, `ITSYBITSY_U2IF`, `QTPY_U2IF` & `QT2040_TRINKEY_U2IF` (admittedly to the same value) pylint complains about duplicate-code.

I did try suppressing the duplicate-code error and failed. However, I've just realised that I might have put it in the wrong file; I suppressed it in `boards` & `chips` but I now think I should have tried `board` Give me an hour to try it again.

**Comment by makermelissa** [comment]
> Unfortunately, that doesn't fix it - it was the first thing I tried.
> The problem is because `board.py` imports `boards` and `chips` which both define `PICO_U2IF`, `FEATHER_U2IF`, `ITSYBITSY_U2IF`, `QTPY_U2IF` & `QT2040_TRINKEY_U2IF` (admittedly to the same value) pylint complains about duplicate-code.
> 

The value is basically the threshold of allowable duplicate lines of code before it throws an error. Too low and it triggers too easily. Too high and it might allow some bad coding.

**Comment by makermelissa** [comment]
Also, you may need to set https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/main/.pylintrc#L22 to 1.

**Comment by lesamouraipourpre** [comment]
**Failure**
`duplicate-code` check can't be disabled - https://github.com/PyCQA/pylint/issues/214
I've also re-tried `min-similarity-lines=100` (stupidly high I know) and it still pops the pylint warning.

Looking at the code in Blinka, I could redo this so that the U2IF constants are **ONLY** defined in `boards` but not in `chips`. The code in `board` would become:
```python
        elif chip_id == boards.PICO_U2IF:
            board_id = boards.PICO_U2IF
        elif chip_id == boards.FEATHER_U2IF:
            board_id = boards.FEATHER_U2IF
        etc.
```

If that seems reasonable to you, I can make and push these changes.

**Comment by lesamouraipourpre** [comment]
These latest commits will, hopefully, keep with the spirit of the chips and boards split. It has a single chip constant `chips.RP2040_U2IF` and maintains the current board constants, eg `boards.PICO_U2IF`.

This will pass `pre-commit` if it is installed in a future PR.

If this PR is merged, it will need a corresponding change made to `Adafruit_Blinka` currently ready to upload from https://github.com/lesamouraipourpre/Adafruit_Blinka/commit/8f9c6b751545645305baba05d8c6260b18f07d68 (A PR would need to be created.)

**Comment by makermelissa** [comment]
I want to take a closer look at Blinka to make sure it won't break anything with the microcontroller name changing before I review this.

**Comment by makermelissa** [comment]
Ok, I only found 1 breaking change from this: https://github.com/adafruit/Adafruit_Blinka/blob/main/src/microcontroller/pin.py#L83

It shouldn't be too difficult to fix, but we should probably get a PR ready before merging this. The nature of this PR is good though.

**Comment by caternuson** [comment]
Thanks. Yah, this looks good. Honestly - what's currently in place was just me being lazy and copy/pasting the same pattern. Looks like there are several others chips that call a private "get id' method in `board.py`, so this refactor is inline with those.

@lesamouraipourpre Did you test this change?

**Comment by lesamouraipourpre** [comment]
> 
> 
> Thanks. Yah, this looks good. Honestly - what's currently in place was just me being lazy and copy/pasting the same pattern. Looks like there are several others chips that call a private "get id' method in `board.py`, so this refactor is inline with those.
> 
> @lesamouraipourpre Did you test this change?

After about 6 hours going insane today trying to get U2IF connecting to Ubuntu (in VMWare) and then Windows I finally tried connecting from a Raspberry Pi 4.

It works like a charm and reports the correct U2IF chip and board.

I've rebased this against the most recent changes to clear the merge conflicts and retested again on the Raspberry Pi 4.

**Review by makermelissa — APPROVED** [review]
This issue is now blocking me, so I'm going to go ahead and approve it.

**Pull request merged**
