### PR TITLE
Fix typing errors for MicroPython

### LINKED ISSUE #220: Typing module not available on Micropython
Blinka, and PlatformDetect are used on micropython, which does not have the typing module, like CP.
A solution would be to escape the imports from typing with try/catch like they are on Circuitpython libraries.

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #220. Tested on Raspberry Pi Pico with latest MicroPython.

### CODE REVIEW

**Comment by makermelissa** [comment]
Ok... weird error.
```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repois0o6nr8/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repois0o6nr8/py_env-python3/lib/python3.7/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repois0o6nr8/py_env-python3/lib/python3.7/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repois0o6nr8/py_env-python3/lib/python3.7/site-packages/click/__init__.py)
```

**Comment by dhalbert** [comment]
See extensive discussion in #circuitpython-dev. Black and click need to be moved up to the latest versions.

**Comment by makermelissa** [comment]
Hmm, this may be problematic:
```
SyntaxError: from __future__ imports must occur at the beginning of the file
```
This requirement pretty much breaks what the PR fixes.

**Comment by makermelissa** [comment]
Testing on Raspberry Pi, enclosing `from __future__ imports` also results in an error. Back to the drawing board on this one.

**Comment by dhalbert** [comment]
> Hmm, this may be problematic:
> 
> ```
> SyntaxError: from __future__ imports must occur at the beginning of the file
> ```
> 
> This requirement pretty much breaks what the PR fixes.

Yes, this is why I added `from __future__ import annotations` to CircuitPython. I guess there could be two versions of what to import.

**Comment by dhalbert** [comment]
The only reason to include `from __future__ import annotations` is to support Python 3.6. Perhaps we should stop supporting that. It breaks Jetson; do you know what else it breaks?

**Comment by makermelissa** [comment]
> The only reason to include `from __future__ import annotations` is to support Python 3.6. Perhaps we should stop supporting that. It breaks Jetson; do you know what else it breaks?

Hmm, let me test without it

**Comment by makermelissa** [comment]
Ok, everything seems to work without it and I'm ok with not having it since we require 3.7 anyways.

**Comment by makermelissa** [comment]
Importing Detector for typing purposes was proving to be problematic without the futures line, so I just removed it. Just a normal detector import (without the TYPE_CHECKING line) caused a circular import issue anyways.

**Comment by makermelissa** [comment]
Sweet, so this was tested on MicroPython, Raspberry Pi, and passed all the the checks.

**Comment by dhalbert** [comment]
I think the Jetson guides will need to describe how to install Python 3.7 or later for user-only use (not updating the system Python). I would expect this is possible. https://forums.developer.nvidia.com/t/python-3-6-approaching-end-of-life/194961 and other places in the that forum discuss using later versions of Python (some successful, some not).

**Comment by makermelissa** [comment]
> I think the Jetson guides will need to describe how to install Python 3.7 or later for user-only use (not updating the system Python). I would expect this is possible. https://forums.developer.nvidia.com/t/python-3-6-approaching-end-of-life/194961 and other places in the that forum discuss using later versions of Python (some successful, some not).

Ok, I'll take a look tomorrow. This PR mainly is for fixing usage on MicroPython.

**Comment by tekktrik** [comment]
Can you add the `from . import XXXXX` to the try/except?  Would it help to escape it in quotes, like `"Detector"`?

**Comment by tekktrik** [comment]
Ah, never mind, sounds like it was causing problems, never mind.

**Comment by makermelissa** [comment]
> I think the Jetson guides will need to describe how to install Python 3.7 or later for user-only use (not updating the system Python). I would expect this is possible. https://forums.developer.nvidia.com/t/python-3-6-approaching-end-of-life/194961 and other places in the that forum discuss using later versions of Python (some successful, some not).

Done. See https://learn.adafruit.com/circuitpython-libraries-on-linux-and-the-nvidia-jetson-nano/initial-setup#install-python-3-dot-7-and-make-default-3114929-19.

**Comment by makermelissa** [comment]
Is this waiting on something from me?

**Comment by tekktrik** [comment]
Not sure if @dhalbert had any followup about `__futures__`, but looking at this now, but you could do the `TYPE_CHECKING` trick for importing detectior in the `try`/`except` I think if you really wanted to keep it.  But with argnames like `detector` I think it's clearly documented either way haha.

**Comment by makermelissa** [comment]
I think I want to leave it out because it's really touchy when trying to get it working all with MicroPython, CPython, and the PyLint.

**Review by tekktrik — APPROVED** [review]
Sounds good!  In that case, the typing looks good!

**Comment by makermelissa** [comment]
Thanks.

**Pull request merged**
