### PR TITLE
added jetson chip and board detect

### PR DESCRIPTION
**Pull request by atan1021**

### CODE REVIEW

**Comment by ladyada** [comment]
@QuantumObstruction hiya wanna try this out?

**Comment by atan1021** [comment]
Need to make an edit, will start a new PR!

**Comment by atan1021** [comment]
Please disregard my my last comment (I deleted it) in case a notification was sent out :)

**Comment by ladyada** [comment]
hiya @atan1021 looks good, please fix up the pylint so we can merge - add the missing docstring. for the too-many-branches you can add a pylint disable.

https://travis-ci.com/adafruit/Adafruit_Python_PlatformDetect/builds/103728046

thanks!

**Comment by QuantumObstruction** [comment]
I got a positive test on the platform detect after I removed the doc string on line 391 """Detect boards."""

I will be testing my TX2 with its sensors this evening using circuit python! Thank you so much for your time. Please advise me if that doc string holds any importance.

**Comment by ladyada** [comment]
@QuantumObstruction what line was it?

**Comment by QuantumObstruction** [comment]
It was a copy paste error. My apologies. Thanks for the help!

**Pull request merged**
