### PR TITLE
Add MCP2221

### PR DESCRIPTION
**Pull request by caternuson**
Add support for Microchip MCP2221 special case controlled by OS environment variable.

**NOTE** - also reworked the general logic in the "special cases" section to remove the try/except blocks.

### CODE REVIEW

**Comment by ladyada** [comment]
needs a lint - also please add a check in the tester sketch that will print out if platformdetect found an mcp2221

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/master/bin/detect.py

**Comment by caternuson** [comment]
Should I have put one of those in for FT232H also?

**Comment by ladyada** [comment]
yah why not :)

**Comment by caternuson** [comment]
I wonder if we should have `board.id` be something like `SPECIAL_CASE` for any of these OS env var set cases? And then `chip.id` would be the actual chip, like `FTDI_FT232H` and `MICROCHIP_MCP2221`.

**Comment by ladyada** [comment]
can do that in a future PR - good enough for now!

**Comment by caternuson** [comment]
cool. works for me.

i'll bump and release.

**Pull request merged**
