### PR TITLE
Add support for NVIDIA Clara AGX Xavier

### PR DESCRIPTION
**Pull request by swarren**

### CODE REVIEW

**Comment by swarren** [comment]
Odd, when I run black locally, it says everything is fine:

```
(venv) [swarren@sprint Adafruit_Python_PlatformDetect]$ python -m black --check --target-version=py35 adafruit_platformdetect/constants/boards.py
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

**Comment by makermelissa** [comment]
Try the latest version of black.

**Comment by swarren** [comment]
I grabbed a fresh install of black from pip, which I assume is the latest? Or do I need to get black from git rather than pip?

**Comment by makermelissa** [comment]
Yeah, I'm just doing `pip3 install --upgrade black`.

**Comment by swarren** [comment]
Nevermind; I found the issue. I'll upload a new version shortly.

**Review by makermelissa — APPROVED** [review]

**Pull request merged**
