### PR TITLE
added Luckfox Mini

### PR DESCRIPTION
**Pull request by nopnop2002**
```
$ cat detect.py
from adafruit_platformdetect import Detector
detector = Detector()
print("Chip id: ", detector.chip.id)
print("Board id: ", detector.board.id)


$ python3 ./detect.py
Chip id:  RV1103
Board id:  LUCKFOX_PICO_MINI
```

### CODE REVIEW

**Comment by makermelissa** [comment]
It looks like it's not passing because of a formatting issue. Running pre-commit and pushing the changes should fix it.

**Comment by nopnop2002** [comment]
@makermelissa 
Thanks for your support.

It was my first time doing PR.
What is pre-commit?

**Comment by makermelissa** [comment]
You can find more info here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Review by makermelissa — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
