### PR TITLE
Make library a bit more readable and maintainable.

### PR DESCRIPTION
**Pull request by yeyeto2788**
Hey guys! 

I know this might be a huge change but, in this PR I'm adding some docstrings and making the code (IMHO) more readable and maintainable.

There are simple things we can do to keep it this way, let me point them here:

 * Blank line before conditionals and loops
* Document variable types on functions and methods docstring (We know that Python is not TypeScrtip but it helps a lot).

As always, I'm open to discussions, comments and possible change requests.

Regards.

### CODE REVIEW

**Comment by hhk7734** [comment]
When will this PR be merged?

**Comment by makermelissa** [comment]
It needs to be updated first or manually merged in. If it's manually merged in, it'll take some time to make sure this isn't a breaking change.

**Comment by yeyeto2788** [comment]
@makermelissa want me to work on this? I opened up this on February and thought maybe I was going too far on this PR because I didn't received any news about it.

**Comment by makermelissa** [comment]
Well, the other major rearrangement broke some incompatibilities and I wanted to look over this more thoroughly, but hadn't had the chance before it got old. Sure, please update. I've implemented Github Actions and Black formatting since then so that should already help.

**Comment by makermelissa** [comment]
Hi, I haven't heard anything in a while, so I'm closing this for now. If you would like to try this again, please let me know. Thanks.

**Pull request closed without merging**
