### PR TITLE
ODROID-COMMON: Classify models by chip vendor

### PR DESCRIPTION
**Pull request by how2flow**
To support pwm on ODROIDs

### CODE REVIEW

**Comment by how2flow** [comment]
> Could you leave the `any_odroid_40_pin` property and just have it check the results of the 3 new functions?

After fixing it, I thought,
Do you want `any_odroid_40_pin` to be used directly from the codes?

**Comment by makermelissa** [comment]
> > Could you leave the `any_odroid_40_pin` property and just have it check the results of the 3 new functions?
> 
> After fixing it, I thought, Do you want `any_odroid_40_pin` to be used directly from the codes?

I'm not 100% sure what you mean, but I mean just have it accessible like it is before this PR in case any code is currently using it to avoid a breaking change. I thought it would make sense for it to just use the yield results from the new functions to simplify maintenance.

**Comment by how2flow** [comment]
> > > Could you leave the `any_odroid_40_pin` property and just have it check the results of the 3 new functions?
> > 
> > 
> > After fixing it, I thought, Do you want `any_odroid_40_pin` to be used directly from the codes?
> 
> I'm not 100% sure what you mean, but I mean just have it accessible like it is before this PR in case any code is currently using it to avoid a breaking change. I thought it would make sense for it to just use the yield results from the new functions to simplify maintenance.

Now that I look at it again, I think we can try using pwmio as generic_linux's. The method is similar, then I don't think we need to distinguish the Odroid board by chip vendor.

It seems that the version conflict and maintenance issues that you are concerned about will also be resolved.
I will push the new one by today after the test.

**Comment by how2flow** [comment]
- https://github.com/adafruit/Adafruit_Blinka/pull/751

There is no problem just reflecting the above commit. Please close this PR as soon as you check this message.

**Pull request closed without merging**
