### PR TITLE
Add Odroid M1 and RK3568B2

### PR DESCRIPTION
**Pull request by MrPanc0**
Add Odroid M1 and RK3568B2 k detekci platformy pro  [Adafruit_Blinka](https://github.com/adafruit/Adafruit_Blinka)

### CODE REVIEW

**Comment by makermelissa** [comment]
You'll want to add the board to `_ODROID_40_PIN_IDS` as well or it won't work for busio: https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/main/adafruit_platformdetect/constants/boards.py#L310

It looks like it's hitting a similar pre-commit reformatting issue which I can help with.

**Review by makermelissa — CHANGES_REQUESTED** [review]
Add board to `_ODROID_40_PIN_IDS`

**Comment by MrPanc0** [comment]
I see sry :) 
and thank you

**Review by makermelissa — APPROVED** [review]
Looks great, thank you.

**Pull request merged**
